### ISSUE TITLE
Add conditional wait to dependency apply steps.

### ISSUE THREAD

**Issue by ctxswitch** [ctxswitch/seaway#61]
We should support conditional blocking wait steps.  I'd like to support the same conditions that kubectl would support, but initially it will probably just be status field checks.

```
wait:
  - namespace: default
     labelSelector:
        app.kubernetes.io/name: pgo
     condition: ready
     timeout: 5m
```
